# Generated by Django 4.2.2 on 2023-09-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('der_Hotelname', models.CharField(max_length=50)),
                ('Entfernung', models.CharField(blank=True, choices=[('Flughafen', 'Flughafen'), ('Senzo Mall', 'Senzo Mall'), ('City Center', 'City Center')], max_length=50, null=True)),
            ],
        ),
    ]
