# Generated by Django 4.2.2 on 2023-09-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='Essen',
            field=models.CharField(blank=True, choices=[('gut', 'gut'), (' sehr gut', ' sehr gut')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='Lage',
            field=models.CharField(blank=True, choices=[('Ausßer', 'Ausßer'), ('gut', 'gut'), ('sehr gut', 'sehr gut')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='Passt',
            field=models.CharField(blank=True, choices=[('Erwachsene', 'Erwachsene'), ('Familien', 'Familien'), ('Familien mit Kinder', 'Familien mit Kinder'), ('Ehepaar', 'Ehepaar')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='Strand',
            field=models.CharField(blank=True, choices=[('Privat', 'Privat'), ('Ohne Strand', 'Ohne Strand'), (' Strand mit Aquapark', ' Strand mit Aquapark')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='preis',
            field=models.CharField(blank=True, choices=[('Günstig', 'Günstig'), ('Mittel', 'Mittel'), ('Teuer', 'Teuer')], max_length=50, null=True),
        ),
    ]
