# Generated by Django 4.2.2 on 2023-09-13 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotels_essen_hotels_lage_hotels_passt_hotels_strand_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotels',
            new_name='Hotel',
        ),
    ]
