# Generated by Django 4.2.2 on 2023-09-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_rename_hotels_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='Foto',
            field=models.ImageField(default=1, upload_to='hotel/%y/%m'),
            preserve_default=False,
        ),
    ]
