# Generated by Django 4.2.2 on 2023-09-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotel_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='hotel/%y/%m'),
        ),
    ]
