# Generated by Django 4.2.2 on 2023-09-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_hotel_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='Staat_Stadt',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
